version: '3'

networks:
  photon:
    external: false

services:
    app:
        environment:
          - DB_HOST=db
          - DB_USER=dev
          - DB_PW=dev
          - DB_PORT=3306
          - DB_DB=dev
          - analyticsPw=dev
        restart: unless-stopped
        depends_on:
          - db
        image: z0pyrus/photon
        volumes:
            - /home/max/git/consts.ts:/app/src/static/scripts/utils/consts.ts
        networks:
          - photon
        ports:
            - "7777:8080"
    db:
        restart: unless-stopped
        image: mariadb
        volumes:
          - /home/max/drive/dockervolumes/photonmaria:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=dev
          - MYSQL_PASSWORD=dev
          - MYSQL_USER=dev
          - MYSQL_DATABASE=dev
        networks:
          - photon
        ports:
           - "3306:3306"