# This is a basic workflow to help you get started with Actions

name: Fork Sync

on:
  schedule:
    - cron: '*/60 17 * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: z0pyrus
          base: Z0pyrus/photon-reddit
          head: ArthurHeitmann/photon-reddit
